### ISSUE TITLE
Pick with mixed return types should generate helpful error

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#103]
Currently, the WHEN part of a pick only accepts a partial for numbers, but allows values for strings.

This does not work:
```
  cause is cause_code:
    pick 'Unknown' when 0
    pick 'Earthquake' when 1
    else 'Not Valid'
```

This does: 
```
  cause is cause_code:
    pick 'Unknown' when = 0
    pick 'Earthquake' when = 1
    else 'Not Valid'
```

The value works when using a string, for example: 
```
color_type is color:
  pick 'simple primary' when 'red' | 'green' | 'blue'
  else 'complex'
```

**Comment by mtoy-googly-moogly** [comment]
OK, what it looks like is that this has nothing to do with strings or numbers ...

`fieldName: pick 'dog' when 'rover' else 'unknown'`

ALSO gets the errror

`fieldName: pick: 'dog' when = 'rover' else 'unknown'`

... works

So I think the bug is that `when` clause  must either be a full boolean expression (like `when someValue > 10 or someValue < 100`), or a partial (like `= 100`), but it cannot be a simple value.

This is different than a `:` operator, because in a `:` you CAN have a simple value as in `someValue : 100` ... but it kind of feels like the thing to right of the `when` should accept anything that goes to the right of the `:`

Before I make this change, I want to make sure I have understood this correctly, @anikaks does this map to your experience?

**Comment by anikaks** [comment]
I think you're right @mtoy-googly-moogly ! sounds great.

**Comment by anikaks** [comment]
Encountering this today. 

This errors about mismatched types:
```
  dimension: agi_size is agi_stub ?
    pick '<$25K' when 1
    pick '$25-50K' when 2
    pick '$50-75K' when 3
    pick '$75-100k' when 4
    pick '$100-200k' when 5
    pick '>$200K' when 6
```

but works if I cast:
```
  dimension: agi_size is agi_stub::string ?
    pick '<$25K' when 1
    pick '$25-50K' when 2
    pick '$50-75K' when 3
    pick '$75-100k' when 4
    pick '$100-200k' when 5
    pick '>$200K' when 6
```

and does not work with an operator (unless I'm using it wrong??)

```
  dimension: agi_size is agi_stub ?
    pick '<$25K' when = 1
    pick '$25-50K' when = 2
    pick '$50-75K' when = 3
    pick '$75-100k' when = 4
    pick '$100-200k' when = 5
    pick '>$200K' when = 6
```

which I think we believed was the issue before, or maybe this is a new issue @mtoy-googly-moogly ?

**Comment by mtoy-googly-moogly** [comment]
you need an else clause ... otherwise the pick might return a string or an integer

**Comment by mtoy-googly-moogly** [comment]
but should definitely be a better error

**Comment by anikaks** [comment]
well that's embarrassing

**Comment by anikaks** [comment]
leaving open to improve error reporting

**Comment by mtoy-googly-moogly** [comment]
OK, I was waiting around for @anikaks to comment but I got impatient.  Here's where I ended up

```
    dimension: pick7 is 7 ? pick 'seven' when 7
=>

Cannot define 'pick7', value has unknown type
pick default type 'number', expected 'string'
```

**Comment by anikaks** [comment]
This looks good to me! Sorry I missed these notifications.....
