### ISSUE TITLE
VSCode issues

### ISSUE THREAD

**Issue by max-sixty** [looker-open-source/malloy#228]
I'm really excited to try Malloy!

I'm trying to get started with VSCode and getting errors. Are these just me? The initial "Edit Connections" page is empty and a bunch of `Not Found` errors in the Dev Tools, including for the "Edit Connections" button:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/5635139/150716714-1d1b7226-d8ad-4e7a-85ae-0a74beb46925.png">

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/5635139/150716817-b9ba3822-e610-4a9f-8480-0d94ac168ab0.png">

**Comment by lloydtabb** [comment]
Sorry, we just released tonight. Actually don't think you need the connection to use bigquery. It's a new part of the UI. If you click away and click back it should redraw.  

Try cutting and pasting one of the samples into it and edit window and seeing if it'll run for you.

**Comment by max-sixty** [comment]
No stress!

I get a schema (which is v cool already), but can't run anything:

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/5635139/150721481-519bcd40-8d3d-4d42-9aa2-edcba2128df2.png">

**Comment by lloydtabb** [comment]
Try clicking away from the connections tab and back to it.  At least that works for me.

Add a connection 'BigQuery'.  Name it 'bigquery' and click any other text field.

The 'Save' button should appear.

**Comment by christopherswenson** [comment]
@max-sixty https://github.com/looker-open-source/malloy/pull/232 should fix the issue with the connection panel not showing up properly. 

The `urlReader is required` error occurred because you ran the "Run Malloy Query" command, which is an internal command used by the "Code Lenses" (buttons that appear inline in the code for running individual queries), and therefore should not have appeared in the command palate. Sorry for the confusion! That PR also hides all the internal commands from the command palate.

You should be able to run the "Run Malloy Query File" command (in future versions of the extension "Malloy: Run Query File"), which will run the last unnamed query in the focused file. That said, we like to use the code lenses to run queries, but in the screenshot you sent, the code lenses don't seem to be visible, and syntax highlighting isn't showing up. We'd love to chat to debug why that's occurring.

**Comment by max-sixty** [comment]
(Thanks so much @christopherswenson — I'll confirm this later today!)

**Comment by max-sixty** [comment]
I tried restarting the editor and running `Run Malloy Query File`. Unfortunately I've been getting the `Compiling` for a couple of minutes:
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/5635139/150926049-613c8a09-2bd8-4f38-8626-a841a56842ca.png">

Let me know any info that would useful. It's already awesome that the schema is there — so something is working already.

**Comment by anikaks** [comment]
Hey @max-sixty a few things we can look at: 

- From this screenshot it looks like maybe you don't have a database connected; can you verify that you have a db connection and whether it's postgres or bigquery? 
- We pushed out fixes for a few issues with connections lat yesterday, so to make absolutely sure you're definitely on the latest, can you try uninstalling the extension, quitting VSCode entirely, then reinstalling? 
- Are there any errors anywhere in the file? do you see anything showing up in the "problems" tab of terminal?


<img width="661" alt="Screen Shot 2022-01-25 at 2 30 18 PM" src="https://user-images.githubusercontent.com/7178946/151070578-51949044-626e-4f05-9937-6ad0bc67b126.png">

**Comment by max-sixty** [comment]
It works! It needed a Reload from a new version of the extension. Thanks — I'm excited to explore!
