### ISSUE TITLE
Generating two `TIMESTAMP_TRUNC()` functions with truncation

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#532]
Given this source/query:
```malloy
source: order_items is table('malloy-data.ecomm.order_items'){
  query: test is {
    group_by: 
      created_day is created_at.week
  }
}
```

We generate
```sql
SELECT 
   TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(order_items.created_at,week),week) as created_week,
   TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(order_items.created_at,month),month) as created_month,
   TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(order_items.created_at,year),year) as created_year,
   TIMESTAMP_TRUNC(TIMESTAMP_TRUNC(order_items.created_at,day),day) as created_day
FROM `malloy-data.ecomm.order_items` as order_items
GROUP BY 1,2,3,4
ORDER BY 1 desc
```

**Comment by anikaks** [comment]
I think this one goes to @mtoy-googly-moogly

**Comment by mtoy-googly-moogly** [comment]
I think this might be a @lloydtabb issue. `created_at.timeframe` generates a truncation, but then the sql writer is, i suspect adding another truncation when it writes the sql for the field because the field has a timeframe.

The compiler must generate the first truncation code. It also must tag the field with a timeframe. I don't know off the top of my head how to make the SQL writer not generate the second truncation.

I feel like the SQL writer is something thinking wrong about timeframes and truncation.

I think the rule needs to be, "if you mark something with a timeframe, you promise that the low bits are zero".

Therefore I think the SQL writer should not be truncating anything.

But I could be wrong.

**Comment by mtoy-googly-moogly** [comment]
Removed me, as we are now just waiting for @lloydtabb and I want my issue list empty :)
