### ISSUE TITLE
composer: dates showing up as NaN-NaN-NaN

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#599]
From

   malloy_examples/data.gov/auto_recall.malloy

Query 'By Year'

![image](https://user-images.githubusercontent.com/1093458/177050300-94f8cc61-d7f0-426f-880f-5cbd35663437.png)

Seems to work ok in VSCode.

Maybe @whscullin ?

**Comment by christopherswenson** [comment]
Is this a discrepancy between BigQuery/Postgres and DuckDB behavior? That comment I added was because we weren't doing anything in particular to standardize the result type of values (in this case for dates) returned from the database. We may want to add a mapping stage which transforms the result into our desired format, using JSON-serialized dates (or something else). I believe BQ has their own Date type which behaves mostly like the JS Date type. I'm not sure about DuckDB or Postgres.

**Comment by whscullin** [comment]
Possibly. DuckDB is definitely directly returning a `Date` object. I'm not sure what the other two are returning offhand.
