### ISSUE TITLE
Malloy:  Error: unknown duckdb type DECIMAL(11,9)

### ISSUE THREAD

**Issue by djouallah** [looker-open-source/malloy#635]
the parquet is parsed fine using the latest version of DuckDB, but I get an error in Malloy

Link to the parquet file

https://drive.google.com/file/d/1gO07g-AwrtTjkMlwZwGY0DJPlVb-1ySO/view?usp=sharing

**Comment by whscullin** [comment]
Thank you for the repro file, it turns out there's actually two issues with that file. First, our `DECIMAL` type handling is inflexible. Fixing that leads to the next issue, though, which is our structure handling only currently works for one level, and there is a nested structure. That will be a little more work to fix, but definitely something we should handle.

**Comment by whscullin** [comment]
Fixed by https://github.com/looker-open-source/malloy/pull/645
